### ISSUE TITLE
Accessing the texture of each triangle?

### ISSUE THREAD

**Issue by cstensonpv** [ywj7931/Hololens_Image_Based_Texture#4]
Hi!
I have been trying to get the texture of each triangle for some image effects and computer vision algorithms. However without success. I'm not the most expeieced when it comes to working with shaders however I believe that the best solution would be to use Garphic.Blit in some way. A the moment I just get a   "random" (certainly not but I can figure out how) squad of each meshfilter.

Any ideas on how we could achieve this?

**Comment by ywj7931** [comment]
Sorry I dont know how

**Comment by cstensonpv** [comment]
I have a solution now that uses orthographic projection against the every triangel and then gets a texture for each triangel in a texture of predefined size.  However it is like taking a picture och a picture and pretty expensive computational. Will try some other approaches without the need to get texture of each triangel now :)
